###DELETE ONE
DELETE http://localhost:3000/comercio/cliente/684abe9f7f16faf8ae89a060

###GET All
GET http://localhost:3000/comercio/cliente

###GET ONE
GET http://localhost:3000/comercio/cliente/6851718939e2c7b4683fcdaa

###GET POR BUSQUEDA
GET http://localhost:3000/comercio/cliente/busqueda/00000000

###MODIFICAR CLIENTE
PUT http://localhost:3000/comercio/cliente/684abeb07f16faf8ae89a064
Content-Type: application/json

{
    "nombre": "Ojeda Sofia"
}

###POST One Cliente
POST http://localhost:3000/comercio/cliente
Content-Type: application/json

{
    "codigo": 6,
    "nombre": "Lorenzatto agustin",
    "telefono": "3456445977",
    "direccion": "Repetto 3345",
    "localidad": "Chajari",
    "email": "AgustinLorenzatto@gmail.com"

}

