###DELETE ONe
DELETE http://localhost:3000/comercio/cuentaCompensada/

###GET FOR CLIENTE
GET http://localhost:3000/comercio/cuentaCompensada/cliente/6851718939e2c7b4683fcdaa

###POST ACTUALIZAR
POST http://localhost:3000/comercio/cuentaCompensada/68593a668507c06fc6c6cfc1

###POST ONE
POST http://localhost:3000/comercio/cuentaCompensada
Content-Type: application/json

{
    "fecha": "2025-06-12",
    "cliente": "6851718939e2c7b4683fcdaa",
    "tipoComprobante": "Comprobante",
    "numeroComprobante": "0001-00000031",
    "importe": 5000,
    "pagado": 0,
    "saldo": 5000,
    "creadoPor": "684c8b934f2e0d9c408e47e2"
}

### PUT ONE
PUT http://localhost:3000/comercio/cuentaCompensada/6859a4175973751d194780e4
Content-Type: application/json

{
    "pagado": 5000,
    "saldo": 0,
    "importe": 5000,
    "cliente": "6851718939e2c7b4683fcdaa",
    "tipoComprobante": "COMPROBANTE",
    "numeroComprobante": "0001-00000032",
    "creadoPor": "684abeb07f16faf8ae89a064"
}