###DELETE ONe
DELETE http://localhost:3000/comercio/cuentaCompensada/

###GET FOR CLIENTE
GET http://localhost:3000/comercio/cuentaCompensada/cliente/6851718939e2c7b4683fcdaa

###POST ACTUALIZAR
POST http://localhost:3000/comercio/cuentaCompensada/68593a668507c06fc6c6cfc1

###POST ONE
POST http://localhost:3000/comercio/cuentaCompensada
Content-Type: application/json

{
    "fecha": "2025-06-12",
    "cliente": "684abeb07f16faf8ae89a064",
    "tipoComprobante": "Comprobante",
    "numeroComprobante": "0001-00000031",
    "importe": 500,
    "pagado": 0,
    "saldo": 500,
    "creadoPor": "684abeb07f16faf8ae89a064"
}

### PUT ONE
PUT http://localhost:3000/comercio/cuentaCompensada/684ac54ea0cbd0e37aa6ce98
Content-Type: application/json

{
    "pagado": 5000,
    "saldo": 0
}