###DELETE
DELETE http://localhost:3000/comercio/movimientoStock/685939d38507c06fc6c6cfa1

###GET ALL
GET http://localhost:3000/comercio/movimientoStock

###GET Por Producto
GET http://localhost:3000/comercio/movimientoStock/producto/685323884877c5304c9add51

###GET Por Tipo y Numero
GET http://localhost:3000/comercio/movimientoStock/porTipoYNumero/COMPROBANTE/0005-00000030


###POST
POST http://localhost:3000/comercio/movimientoStock
Content-Type: application/json

{
    "producto": "685323884877c5304c9add51",
    "tipo": "comprobante",
    "cantidad": 1,
    "precio": 5000,
    "stockAntes": 9,
    "stockAhora": 8,
    "detalle": "",
    "numeroComprobante": "0001-00000031",
    "creadoPor": "684c8b934f2e0d9c408e47e2"
}

###PUT 
PUT http://localhost:3000/comercio/movimientoStock/68593c2cab049c33cce9b1d9
Content-Type: application/json

 {
      "producto": "6853f4c1afd809a128aeaee5",
      "tipo": "COMPROBANTE",
      "cantidad": -3,
      "stockAntes": 6,
      "precio": 500,
      "stockAhora": 9,
      "detalle": "",
      "numeroComprobante": "0001-00000031",
      "creadoPor": "684c8b934f2e0d9c408e47e2",
      "fecha": "2025-06-19T13:49:01.783Z"
    }