###DELETe
DELETE http://localhost:3000/comercio/producto/6851fc6323a52d62d5ae7949

###GET
GET http://localhost:3000/comercio/producto

###GET ONE 
GET http://localhost:3000/comercio/producto/684c1720f2b2fc34930e18d9

###POST ONE
POST http://localhost:3000/comercio/producto
Content-Type: application/json

{
    "codigo": "035-019",
    "codigoFabrica": "fabrica",
    "descripcion": "Galletita de Arroz 100G",
    "marca": "684abe9f7f16faf8ae89a060",
    "costo": 1500,
    "iva": 21,
    "utilidad": 50,
    "precio": 2720,
    "stock": 50,
    "stockMinimo": 5
    
}

### PUT ONE
PUT http://localhost:3000/comercio/producto/684c1720f2b2fc34930e18d9
Content-Type: application/json

{
    "activo": false
}
