#GET ALLL
GET http://localhost:3000/comercio/remito

###POST One
POST http://localhost:3000/comercio/remito
Content-Type: application/json

{
    "cliente": "684abeb07f16faf8ae89a064",
    "nombreCliente": "Ojeda Sofia",
    "tipoComprobante": "REMITO",
    "numeroComprobante": "RT-0001-00000001",
    "pasado": false
}