###DELETE ONE
DELETE http://localhost:3000/comercio/remito/68629125d455b6721df65279

###GET ALLL
GET http://localhost:3000/comercio/remito

###POST One
POST http://localhost:3000/comercio/remito
Content-Type: application/json

{
    "cliente": "6851718939e2c7b4683fcdaa",
    "nombreCliente": "Ojeda Sofia",
    "tipoComprobante": "REMITO",
    "numeroComprobante": "RT-0001-00000003",
    "pasado": true
}