
###DELETE ONE
DELETE http://localhost:3000/comercio/tipoTarjeta/684c7d7076ceac859fd8b046

###GET ALL
GET http://localhost:3000/comercio/tipoTarjeta

###GET ONE
GET http://localhost:3000/comercio/tipoTarjeta/684c7d7076ceac859fd8b046

###GET NOMBRES
GET http://localhost:3000/comercio/tipoTarjeta/nombres

### POST ONE
POST http://localhost:3000/comercio/tipoTarjeta
Content-Type: application/json

{
    "nombre": "VISA",
    "tipo": "CREDITO"
}


###PUT ONE 
PUT http://localhost:3000/comercio/tipoTarjeta/684c7d7076ceac859fd8b046
Content-Type: application/json

{
    "nombre": "VISA DEBITO",
    "tipo": "DEBITO"
}